More lifting of a few API functions
IagoAbal/haskell-z3 pull request #59
Opened 2021-02-26 10:10 UTC by maurobringolf

Two interesting things:

1. I introduced `returnValueToMaybe :: Monad m => Bool -> m a -> m (Maybe a)`, but then found out that this exists in `Control.Monad.Extra` as `whenMaybe`. So I replaced my own with this dependency, but if you favor dropping the dependency and keeping our own implementation I can undo the last commit.
2. I couldn't think of a way to test `isWellSorted` since ASTs constructed through the API are always well sorted as far as I can tell. But now that I am writing this I realize that it might be possible by directly manipulating an AST through `poke`.

2021-03-04 23:24 UTC, IagoAbal requested changes
As usual it looks good, I would just prefer to avoid depending on _extra_.

2021-03-04 23:24 UTC, IagoAbal commented on z3.cabal
> +                         extra,
Could you create an internal module `Z3.Common` and add your own version of `whenMaybe` there?

2021-03-05 12:45 UTC, maurobringolf commented on z3.cabal
> +                        Example.Monad.IntList
Piggy-backing this fix for a compiler warning introduced by my recent PR.

2021-03-05 12:46 UTC, maurobringolf commented
I moved the function to `Z3.Common`. Let me know if you had a different structure in mind. I also rebased.

2021-03-05 16:50 UTC, IagoAbal approved these changes
Perfect, thanks!

2021-03-05 16:55 UTC, merged